### ISSUE TITLE
Allow subscripting the last index of the array

### ISSUE THREAD

**Issue by nakib** [wavebitscientific/functional-fortran#26] opened 2022-11-13 14:02 UTC
Hello!

Thank you for taking the time to work on this great project!

I noticed that the subscript function does not work for the last element of the array. For example, `print*, subscript(-arange(1, 10), [1, 3, 9, 10])` gives `-1  -3  -9`, instead of the expected `-1  -3  -9  -10`. This can be fixed by replacing `indices = pack(ind, ind > 0 .and. ind < size(x))` with `indices = pack(ind, ind > 0 .and. ind <= size(x))` in the functions subscript_*. I could create a pull request if you agree that this should be the expected behavior (or you can fix it yourself in a minute).

Related point. There is a lot of code duplication needed to handle the various types. Using templates (https://github.com/SCM-NV/ftl) would help with this.

Best regards,
Nakib

**Comment by milancurcic** [comment] 2022-11-16 16:36
Thank you for reporting this. I can reproduce it. Yes, please submit a PR, your fix looks correct to me.

Indeed, there is a lot of duplicated code here. This is because I wanted a preprocessor free solution, and the duplication is done only once. A lot of duplication could be reduced using the standard `include` statement, but that would require many more .inc source files in addition to the library .f90. I'm certainly open to looking into alternatives, and there are many (e.g. C-preprocessor, fypp, include statements).

**Comment by nakib** [comment] 2022-11-16 20:40
Thanks. Created a PR just now.

Best,
Nakib

**Comment by milancurcic** [comment] 2022-12-07 22:44
Fixed by #27

**Closed as completed by milancurcic** 2022-12-07 22:44 UTC
Labels: bug
